# This file was generated by GoReleaser. DO NOT EDIT.
cask "fallbakit" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "6b8046255cc1a45958e56ea9ef6a665346746b644ecb66e996dcaa67da9e317b"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "31cc2a985bfd7c26fba808cabb00b683da39c3cdc9e349a5feded591b0a0d75d"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "44cecd052c542829354e9c359b391422e24ce2f4565c5aa474d84c4864701a25"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5557c52da46dd9d61c8a7460e28ebc047de570ff14b3b342b1df8e96f1e3af9"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fallbakit"
  desc "Local-first AI inference with cloud fallback — developer CLI"
  homepage "https://fallbakit.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fallbakit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fallbakit"]
    end
  end

  # No zap stanza required

end
