# This file was generated by GoReleaser. DO NOT EDIT.
cask "fallbakit" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "17d657e0a3abf2bdcd5520fbe9f3d0bf28dfcb4cb2f0f3b03f5de4ef920f9143"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "19872594bf8007bfe6e5df21a7cba76b853154759281ae2dd78593e4f6734d6e"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce8077e14f7ac8a46c3a69a90bb0c7b5fb0a27cfd7c17fe0fdcf7674b0dd9e89"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffac46608537cd3fe3f373340a47e175c9a531960d9d760cc79bdb10626ff4df"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fallbakit"
  desc "Local-first AI inference with cloud fallback — developer CLI"
  homepage "https://fallbakit.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fallbakit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fallbakit"]
    end
  end

  # No zap stanza required

end
