# This file was generated by GoReleaser. DO NOT EDIT.
cask "fallbakit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "edd082dca7328ed4739926b429e42146a60eeeb8963549f3fa9349d85247eaf8"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c87aca5f5389262d917c6a2df016c82a551b700fd68f244fc1978893cdbaf683"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "656c9d3030950c5e4cb821ccd8205e1c314bf008594551c9c016d059d45894c8"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59c87929adb7c2aa83e1a9332d107a2dcf09fbd15a12c7f4e7ee90033bc91b82"
      url "https://github.com/fallbakit/cli/releases/download/v#{version}/fallbakit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fallbakit"
  desc "Local-first AI inference with cloud fallback — developer CLI"
  homepage "https://fallbakit.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fallbakit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fallbakit"]
    end
  end

  # No zap stanza required

end
